services:
  - type: web
    name: stl-to-3mf-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 